// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_spotify_access_token from "./routes/api/spotify/access-token.ts";
import * as $api_spotify_refresh_token from "./routes/api/spotify/refresh-token.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $spotify_login from "./routes/spotify/login.tsx";
import * as $tracks from "./routes/tracks.tsx";
import * as $Counter from "./islands/Counter.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/spotify/access-token.ts": $api_spotify_access_token,
    "./routes/api/spotify/refresh-token.ts": $api_spotify_refresh_token,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/spotify/login.tsx": $spotify_login,
    "./routes/tracks.tsx": $tracks,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
