create table if not exists public.users (
  user_id uuid primary key references neon_auth.user(id) on delete cascade,
  spotify_token jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.searches (
  id integer generated by default as identity primary key,
  user_id uuid not null references neon_auth.user(id) on delete cascade,
  search text not null,
  created_at timestamptz not null default now(),
  unique (user_id, search)
);

create index if not exists searches_user_id_id_idx
  on public.searches (user_id, id desc);

grant usage on schema public to authenticated;

grant select, insert, update on public.users to authenticated;

alter table public.users enable row level security;

drop policy if exists users_select_own on public.users;
create policy users_select_own on public.users
  for select
  to authenticated
  using (user_id = auth.uid());

drop policy if exists users_insert_own on public.users;
create policy users_insert_own on public.users
  for insert
  to authenticated
  with check (user_id = auth.uid());

drop policy if exists users_update_own on public.users;
create policy users_update_own on public.users
  for update
  to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

grant select, insert, update, delete on public.searches to authenticated;
grant usage, select on sequence public.searches_id_seq to authenticated;

alter table public.searches enable row level security;

drop policy if exists searches_select_own on public.searches;
create policy searches_select_own on public.searches
  for select
  to authenticated
  using (user_id = auth.uid());

drop policy if exists searches_insert_own on public.searches;
create policy searches_insert_own on public.searches
  for insert
  to authenticated
  with check (user_id = auth.uid());

drop policy if exists searches_update_own on public.searches;
create policy searches_update_own on public.searches
  for update
  to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

drop policy if exists searches_delete_own on public.searches;
create policy searches_delete_own on public.searches
  for delete
  to authenticated
  using (user_id = auth.uid());
