create table if not exists public.app_sessions (
  token_hash text primary key,
  user_id uuid not null references neon_auth.user(id) on delete cascade,
  user_email text,
  user_name text,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

create table if not exists public.users (
  user_id uuid primary key references neon_auth.user(id) on delete cascade,
  spotify_token jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.searches (
  id integer generated by default as identity primary key,
  user_id uuid not null references neon_auth.user(id) on delete cascade,
  search text not null,
  created_at timestamptz not null default now(),
  unique (user_id, search)
);

create table if not exists public.chat_threads (
  id integer generated by default as identity primary key,
  user_id uuid not null references neon_auth.user(id) on delete cascade,
  title text not null,
  openai_conversation_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.chat_messages (
  id integer generated by default as identity primary key,
  thread_id integer not null references public.chat_threads(id) on delete cascade,
  user_id uuid not null references neon_auth.user(id) on delete cascade,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  song_cards jsonb,
  openai_response_id text,
  created_at timestamptz not null default now()
);

create index if not exists searches_user_id_id_idx
  on public.searches (user_id, id desc);

create index if not exists app_sessions_user_id_idx
  on public.app_sessions (user_id);

create index if not exists chat_threads_user_updated_idx
  on public.chat_threads (user_id, updated_at desc);

create index if not exists chat_messages_thread_id_id_idx
  on public.chat_messages (thread_id, id asc);

create index if not exists chat_messages_user_thread_id_idx
  on public.chat_messages (user_id, thread_id, id asc);

grant usage on schema public to authenticated;

grant select, insert, update on public.users to authenticated;

alter table public.users enable row level security;

drop policy if exists users_select_own on public.users;
create policy users_select_own on public.users
  for select
  to authenticated
  using (user_id = auth.uid());

drop policy if exists users_insert_own on public.users;
create policy users_insert_own on public.users
  for insert
  to authenticated
  with check (user_id = auth.uid());

drop policy if exists users_update_own on public.users;
create policy users_update_own on public.users
  for update
  to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

grant select, insert, update, delete on public.searches to authenticated;
grant usage, select on sequence public.searches_id_seq to authenticated;

alter table public.searches enable row level security;

drop policy if exists searches_select_own on public.searches;
create policy searches_select_own on public.searches
  for select
  to authenticated
  using (user_id = auth.uid());

drop policy if exists searches_insert_own on public.searches;
create policy searches_insert_own on public.searches
  for insert
  to authenticated
  with check (user_id = auth.uid());

drop policy if exists searches_update_own on public.searches;
create policy searches_update_own on public.searches
  for update
  to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

drop policy if exists searches_delete_own on public.searches;
create policy searches_delete_own on public.searches
  for delete
  to authenticated
  using (user_id = auth.uid());

grant select, insert, update, delete on public.chat_threads to authenticated;
grant usage, select on sequence public.chat_threads_id_seq to authenticated;

alter table public.chat_threads enable row level security;

drop policy if exists chat_threads_select_own on public.chat_threads;
create policy chat_threads_select_own on public.chat_threads
  for select
  to authenticated
  using (user_id = auth.uid());

drop policy if exists chat_threads_insert_own on public.chat_threads;
create policy chat_threads_insert_own on public.chat_threads
  for insert
  to authenticated
  with check (user_id = auth.uid());

drop policy if exists chat_threads_update_own on public.chat_threads;
create policy chat_threads_update_own on public.chat_threads
  for update
  to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

drop policy if exists chat_threads_delete_own on public.chat_threads;
create policy chat_threads_delete_own on public.chat_threads
  for delete
  to authenticated
  using (user_id = auth.uid());

grant select, insert, update, delete on public.chat_messages to authenticated;
grant usage, select on sequence public.chat_messages_id_seq to authenticated;

alter table public.chat_messages enable row level security;

drop policy if exists chat_messages_select_own on public.chat_messages;
create policy chat_messages_select_own on public.chat_messages
  for select
  to authenticated
  using (user_id = auth.uid());

drop policy if exists chat_messages_insert_own on public.chat_messages;
create policy chat_messages_insert_own on public.chat_messages
  for insert
  to authenticated
  with check (user_id = auth.uid());

drop policy if exists chat_messages_update_own on public.chat_messages;
create policy chat_messages_update_own on public.chat_messages
  for update
  to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

drop policy if exists chat_messages_delete_own on public.chat_messages;
create policy chat_messages_delete_own on public.chat_messages
  for delete
  to authenticated
  using (user_id = auth.uid());
