create table if not exists public.users (
  user_id uuid primary key references neon_auth.user(id) on delete cascade,
  spotify_token jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.searches (
  id integer generated by default as identity primary key,
  user_id uuid not null references neon_auth.user(id) on delete cascade,
  search text not null,
  created_at timestamptz not null default now(),
  unique (user_id, search)
);

create index if not exists searches_user_id_id_idx
  on public.searches (user_id, id desc);
